ID: 2026Y-02M-07D-18h33m49s_Zn3A
PID: 411856
START_DATETIME: 2026-02-07 18:33:49.599650
FILE:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed.py
SDIR_OUT:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out
SDIR_RUN:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out/RUNNING/2026Y-02M-07D-18h33m49s_Zn3A-main
ARGS: {}
EXIT_STATUS: 1
END_DATETIME: 2026-02-07 18:33:52.318471
RUN_DURATION: 00:00:02
