ID: 2026Y-02M-07D-18h41m47s_JWpU
PID: 437446
START_DATETIME: 2026-02-07 18:41:47.743937
FILE: /home/ywatanabe/proj/figrecipe/examples/09b_diagram_NG_patterns.py
SDIR_OUT: /home/ywatanabe/proj/figrecipe/examples/09b_diagram_NG_patterns_out
SDIR_RUN:
    /home/ywatanabe/proj/figrecipe/examples/09b_diagram_NG_patterns_out/RUNNING/2026Y-02M-07D-18h41m47s_JWpU-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2026-02-07 18:41:50.272645
RUN_DURATION: 00:00:02
