ID: 2026Y-02M-14D-18h38m25s_40fK
PID: 1628452
START_DATETIME: 2026-02-14 18:38:25.257715
FILE: /home/ywatanabe/proj/figrecipe/examples/09d_diagram_autofix.py
SDIR_OUT: /home/ywatanabe/proj/figrecipe/examples/09d_diagram_autofix_out
SDIR_RUN: 
    /home/ywatanabe/proj/figrecipe/examples/09d_diagram_autofix_out/RUNNING/2026Y-02M-14D-18h38m25s_40fK-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2026-02-14 18:38:29.272121
RUN_DURATION: 00:00:04
