ID: 2026Y-02M-07D-18h25m41s_dO23
PID: 381694
START_DATETIME: 2026-02-07 18:25:41.993550
FILE:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed.py
SDIR_OUT:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out
SDIR_RUN:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out/RUNNING/2026Y-02M-07D-18h25m41s_dO23-main
ARGS: {}
EXIT_STATUS: 1
END_DATETIME: 2026-02-07 18:25:45.099091
RUN_DURATION: 00:00:03
