/** Delayed real-client reads and real store reset across project sessions. */
import assert from "node:assert/strict";
import { build } from "esbuild";
import { fileURLToPath } from "node:url";
const source=fileURLToPath(new URL("../src/",import.meta.url));
const bundle=await build({stdin:{contents:'export * from "./api/client"; export {useEditorStore,resetEditorWorkspace} from "./store/useEditorStore";',resolveDir:source,loader:"ts"},bundle:true,write:false,format:"esm",platform:"node",define:{"import.meta.env.VITE_API_BASE":'""'}});
globalThis.window={location:{search:"?project=old-url&recipe=old.yaml"}};
globalThis.document={cookie:"csrftoken=synthetic-token"};
globalThis.localStorage={getItem:()=>null,setItem(){}};
const leaf=await import("data:text/javascript;base64,"+Buffer.from(bundle.outputFiles[0].text).toString("base64"));
leaf.setApiBase("/custom/plot");leaf.setWorkingDir("/synthetic/A");leaf.setRecipe("a.yaml");leaf.setProject("A");
let resolveBody, receivedOptions;
globalThis.fetch=async (_url,options)=>{receivedOptions=options;return {ok:true,json:()=>new Promise(resolve=>{resolveBody=resolve})};};
const read=leaf.api.get("preview");
await new Promise(resolve=>setImmediate(resolve));
leaf.setProject("B");leaf.setWorkingDir("/synthetic/B");leaf.setRecipe("b.yaml");
assert.equal(receivedOptions.signal.aborted,true);
resolveBody({image:"OLD A"});
await assert.rejects(read,leaf.ApiSessionExpired);
const url=new URL(leaf.apiUrl("preview"),"https://fixture.invalid");
assert.equal(url.searchParams.get("project"),"B");
assert.equal(url.searchParams.get("recipe"),"b.yaml");
assert.equal(url.searchParams.get("working_dir"),"/synthetic/B");

leaf.useEditorStore.setState({placedFigures:[],currentFile:"a.yaml",clipboard:{path:"a.yaml"},datatableTabs:{old:{rows:[["OLD A"]]}},darkMode:true});
const preview=leaf.useEditorStore.getState().loadPreview();
await new Promise(resolve=>setImmediate(resolve));
leaf.retireApiSession();leaf.resetEditorWorkspace();
leaf.useEditorStore.setState({currentFile:"b.yaml",loading:true});
resolveBody({image:"OLD A",bboxes:{},img_size:{width:100,height:100}});
await preview;
const state=leaf.useEditorStore.getState();
assert.equal(state.currentFile,"b.yaml");assert.deepEqual(state.placedFigures,[]);
assert.deepEqual(state.datatableTabs,{});assert.equal(state.clipboard,null);
assert.equal(state.darkMode,true);assert.equal(state.loading,true);assert.equal(state.toast,null);
// A failed outgoing inspector read must not clear B's same-named axes/cell.
const calls=leaf.useEditorStore.getState().loadCalls(0);
await new Promise(resolve=>setImmediate(resolve));
leaf.retireApiSession();leaf.useEditorStore.setState({calls:{"0":[{method:"B"}]}});
resolveBody({calls:[{method:"OLD A"}]});await calls;
assert.deepEqual(leaf.useEditorStore.getState().calls,{"0":[{method:"B"}]});
leaf.useEditorStore.setState({selectedElement:"same",elementDetails:{label:"A"}});
const details=leaf.useEditorStore.getState().loadElementDetails();
await new Promise(resolve=>setImmediate(resolve));
leaf.retireApiSession();leaf.useEditorStore.setState({selectedElement:"same",elementDetails:{label:"B"}});
resolveBody({label:"OLD A"});await details;
assert.deepEqual(leaf.useEditorStore.getState().elementDetails,{label:"B"});
leaf.setProject("");leaf.setRecipe("");leaf.setWorkingDir("");leaf.setApiBase("");
const root=new URL(leaf.apiUrl("preview"),"https://fixture.invalid");
assert.equal(root.pathname,"/preview");assert.equal(root.search,"");
console.log("workspaceSession: expired JSON rejected; outgoing store response/clipboard/table cleared; preferences retained; explicit root blocks stale URL selectors");
