ID: 2026Y-02M-07D-18h33m56s_LiZU
PID: 413621
START_DATETIME: 2026-02-07 18:33:56.916037
FILE:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed.py
SDIR_OUT:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out
SDIR_RUN:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out/RUNNING/2026Y-02M-07D-18h33m56s_LiZU-main
ARGS: {}
EXIT_STATUS: 1
END_DATETIME: 2026-02-07 18:33:59.546653
RUN_DURATION: 00:00:02
