"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'figrecipe' references
in its source tree. Two outcomes:

- Module installed AND import succeeds -> test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` -> `scitex_io._loading._load_cache`) ->
  test FAILS loudly.
- ROOT distribution NOT installed (peer standalone absent in a lean
  env) -> test is SKIPPED. The skip is decided on the root package
  ONLY, never on the full dotted path -- see the test body.
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex_app",
    "scitex_app._django",
    "scitex_app._standalone",
    "scitex_browser.debugging",
    "scitex_config",
    "scitex_config._ecosystem",
    "scitex_dev",
    "scitex_dev._branding",
    "scitex_dev.cli",
    "scitex_dev.linter._fm_checker",
    "scitex_dev.linter._rules._base",
    "scitex_dev.ecosystem",
    "scitex_dev.linter.checker",
    "scitex_logging",
    "scitex_pd",
    "scitex_types",
    "scitex_ui",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_declared_cross_package_dependency_imports(module_name):
    """Importing figrecipe's declared cross-package dependency must succeed."""
    # Arrange — skip on the ROOT distribution only. `importorskip` given the
    # full dotted path cannot distinguish "peer not installed" from "peer
    # installed, submodule renamed", and answers SKIP to both. That is not
    # hypothetical: `scitex_dev.skills` moved to `scitex_dev.ecosystem` and this
    # gate reported a skip while src/figrecipe/_mcp/server.py still imported the
    # old path, so figrecipe's skills_list/skills_get MCP tools raised
    # ModuleNotFoundError on every call and the gate stayed green.
    pytest.importorskip(module_name.split(".")[0])

    # Act — hard-import the FULL path. The root is present, so a failure here is
    # a real breakage rather than a legitimately absent optional peer.
    mod = importlib.import_module(module_name)

    # Assert
    assert mod.__name__ == module_name
