ID: 2026Y-02M-07D-18h47m32s_UhUu
PID: 458768
START_DATETIME: 2026-02-07 18:47:32.895524
FILE:
    /home/ywatanabe/proj/figrecipe/examples/10a_figrecipe_concept_diagram_error.py
SDIR_OUT:
    /home/ywatanabe/proj/figrecipe/examples/10a_figrecipe_concept_diagram_error_out
SDIR_RUN:
    /home/ywatanabe/proj/figrecipe/examples/10a_figrecipe_concept_diagram_error_out/RUNNING/2026Y-02M-07D-18h47m32s_UhUu-main
ARGS: {}
EXIT_STATUS: 1
END_DATETIME: 2026-02-07 18:47:35.788921
RUN_DURATION: 00:00:02
