ID: 2026Y-02M-07D-18h32m06s_iLCl
PID: 406415
START_DATETIME: 2026-02-07 18:32:06.132130
FILE:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed.py
SDIR_OUT:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out
SDIR_RUN:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out/RUNNING/2026Y-02M-07D-18h32m06s_iLCl-main
ARGS: {}
EXIT_STATUS: 1
END_DATETIME: 2026-02-07 18:32:08.993019
RUN_DURATION: 00:00:02
