"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def test_audit_all_for_package_reports_clean():
    # Arrange
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    # Act
    # `audit_all_for_package` raises (pytest.fail) on any violation;
    # a clean return is the assertion proxy.
    audit_all_for_package(
        "figrecipe",
        skip_rules=(
            # MCP <-> Python-API parity gap: 74 MCP tools (mostly
            # diagram_*, e.g. diagram_compile_graphviz / diagram_create)
            # are thin wrappers around external CLIs (graphviz / mermaid /
            # plantuml) with no Python-API counterpart by design. The
            # auditor's pairing rule (§6) flags every one as architectural
            # debt; per-tool decisions are tracked under /overhaul-scitex.
            # Same escape pattern as scitex-clew and scitex-notebook.
            "§6",
        ),
    )
    # Assert
    assert True  # `audit_all_for_package` raises on failure
