"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


@pytest.mark.skipif(
    shutil.which("scitex-dev") is None,
    reason=(
        "scitex-dev not installed — add `scitex-dev[cli-audit]` "
        "to [project.optional-dependencies.dev]"
    ),
)
def test_audit_all_for_package_reports_clean():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    # Act
    # `audit_all_for_package` raises (pytest.fail) on any violation;
    # a clean return is the assertion proxy.
    audit_all_for_package(
        "figrecipe",
        skip_rules=(
            # MCP <-> Python-API parity gap: 74 MCP tools (mostly
            # diagram_*, e.g. diagram_compile_graphviz / diagram_create)
            # are thin wrappers around external CLIs (graphviz / mermaid /
            # plantuml) with no Python-API counterpart by design. The
            # auditor's pairing rule (§6) flags every one as architectural
            # debt.
            #
            # The DECLARED exemption now lives in pyproject.toml as
            # `[tool.scitex_dev] mcp_parity_exempt = true`. This skip_rules
            # entry is the TRANSITIONAL fallback: CI installs scitex-dev
            # from PyPI (`scitex-dev>=0.11.7`), and the mcp_parity_exempt
            # knob only suppresses §6 once a scitex-dev release carrying it
            # is published and the pin is bumped. Until then, the knob is a
            # forward-compatible no-op and this entry keeps pytest-matrix
            # green. Remove this entry (keeping the pyproject declaration)
            # after bumping scitex-dev to the version with the knob.
            "§6",
        ),
    )
    # Assert
    assert True  # `audit_all_for_package` raises on failure
