"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil
from pathlib import Path

import pytest


@pytest.mark.skipif(
    shutil.which("scitex-dev") is None,
    reason=(
        "scitex-dev not installed — add `scitex-dev[cli-audit]` "
        "to [project.optional-dependencies.dev]"
    ),
)
def test_audit_all_for_package_reports_clean():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    # Act
    # `audit_all_for_package` raises (pytest.fail) on any violation;
    # a clean return is the assertion proxy. The §6 MCP<->Python-API
    # parity rule is exempted via `.scitex/dev/config.yaml`
    # (audit.mcp-parity-exempt: true), read by scitex-dev >= 0.12.0.
    # `path=` anchors the audit on THIS checkout — the tree this test file
    # lives in. Without it the audit resolves "figrecipe" by import location
    # or a ~/proj/<name> guess and grades WHATEVER tree sits there, not the
    # commit under test. That is not hypothetical: through 2026-07-21 the CI
    # gate graded a stale checkout on the runner host — false-failing PR #312
    # on a pre-commit hook deleted in #306, and false-passing the 8 violations
    # later fixed in #321, which had shipped through a green gate. A gate that
    # grades the wrong tree is worse than no gate (scitex-dev's own docstring
    # for `path`, which prescribes exactly this anchor).
    # timeout override of the generated 120s default: audit-all runs clean in
    # ~55s standalone but exceeds 120s inside the pytest-matrix SIF (coverage +
    # parallel load), flaking every PR. 300s is a realistic cap for a
    # slow-but-clean audit. (scitex-dev owns the write-audit-test default.)
    audit_all_for_package(
        "figrecipe",
        path=Path(__file__).resolve().parents[2],
        timeout=300,
    )
    # Assert
    assert True  # `audit_all_for_package` raises on failure
