ID: 2026Y-02M-07D-04h05m01s_fju6
PID: 2420980
START_DATETIME: 2026-02-07 04:05:01.284932
FILE: /home/ywatanabe/proj/figrecipe/examples/09_diagram.py
SDIR_OUT: /home/ywatanabe/proj/figrecipe/examples/09_diagram_out
SDIR_RUN:
    /home/ywatanabe/proj/figrecipe/examples/09_diagram_out/RUNNING/2026Y-02M-07D-04h05m01s_fju6-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2026-02-07 04:05:05.431999
RUN_DURATION: 00:00:04
