ID: 2026Y-02M-07D-18h27m53s_4rOn
PID: 388323
START_DATETIME: 2026-02-07 18:27:53.723297
FILE:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed.py
SDIR_OUT:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out
SDIR_RUN:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out/RUNNING/2026Y-02M-07D-18h27m53s_4rOn-main
ARGS: {}
EXIT_STATUS: 1
END_DATETIME: 2026-02-07 18:27:56.661343
RUN_DURATION: 00:00:02
