ID: 2026Y-02M-07D-18h32m00s_OrwF
PID: 405357
START_DATETIME: 2026-02-07 18:32:00.208535
FILE:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed.py
SDIR_OUT:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out
SDIR_RUN:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out/RUNNING/2026Y-02M-07D-18h32m00s_OrwF-main
ARGS: {}
EXIT_STATUS: 1
END_DATETIME: 2026-02-07 18:32:03.271751
RUN_DURATION: 00:00:03
