ID: 2026Y-02M-07D-18h39m19s_1PGr
PID: 429389
START_DATETIME: 2026-02-07 18:39:19.847480
FILE:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed.py
SDIR_OUT:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out
SDIR_RUN:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out/RUNNING/2026Y-02M-07D-18h39m19s_1PGr-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2026-02-07 18:39:23.998014
RUN_DURATION: 00:00:04
