ID: 2026Y-02M-07D-18h46m14s_AzR3
PID: 452841
START_DATETIME: 2026-02-07 18:46:14.530222
FILE:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed.py
SDIR_OUT:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out
SDIR_RUN:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out/RUNNING/2026Y-02M-07D-18h46m14s_AzR3-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2026-02-07 18:46:18.990039
RUN_DURATION: 00:00:04
