ID: 2026Y-02M-07D-19h23m28s_rlqy
PID: 593291
START_DATETIME: 2026-02-07 19:23:28.064629
FILE: 
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed.py
SDIR_OUT: 
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out
SDIR_RUN: 
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out/RUNNING/2026Y-02M-07D-19h23m28s_rlqy-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2026-02-07 19:23:32.241379
RUN_DURATION: 00:00:04
