ID: 2026Y-02M-07D-18h28m40s_ZtaQ
PID: 391405
START_DATETIME: 2026-02-07 18:28:40.661340
FILE:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed.py
SDIR_OUT:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out
SDIR_RUN:
    /home/ywatanabe/proj/figrecipe/examples/10b_figrecipe_concept_diagram_fixed_out/RUNNING/2026Y-02M-07D-18h28m40s_ZtaQ-main
ARGS: {}
EXIT_STATUS: 1
END_DATETIME: 2026-02-07 18:28:43.600449
RUN_DURATION: 00:00:02
