ID: 2026Y-02M-07D-04h01m52s_vEs9
PID: 2407846
START_DATETIME: 2026-02-07 04:01:52.900929
FILE: /home/ywatanabe/proj/figrecipe/examples/09_diagram.py
SDIR_OUT: /home/ywatanabe/proj/figrecipe/examples/09_diagram_out
SDIR_RUN:
    /home/ywatanabe/proj/figrecipe/examples/09_diagram_out/RUNNING/2026Y-02M-07D-04h01m52s_vEs9-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2026-02-07 04:01:57.326159
RUN_DURATION: 00:00:04
