ID: 2026Y-02M-07D-18h53m26s_1EL3
PID: 477903
START_DATETIME: 2026-02-07 18:53:26.013155
FILE:
    /home/ywatanabe/proj/figrecipe/examples/10a_figrecipe_concept_diagram_error.py
SDIR_OUT:
    /home/ywatanabe/proj/figrecipe/examples/10a_figrecipe_concept_diagram_error_out
SDIR_RUN:
    /home/ywatanabe/proj/figrecipe/examples/10a_figrecipe_concept_diagram_error_out/RUNNING/2026Y-02M-07D-18h53m26s_1EL3-main
ARGS: {}
EXIT_STATUS: 1
END_DATETIME: 2026-02-07 18:53:28.901628
RUN_DURATION: 00:00:02
